export default {
    common: [
        'Broken',
        'Electric',
        'Fire',
        'Gamble',
        'Ice',
        'Iron',
        'Lock',
        'Poison',
        'Wind',
    ],
    rare: [
        'Crack',
        'Critical',
        'Crossbow',
        'Energy',
        'Light',
        'Mine',
        'Sacrificial',
        'Thorn',
    ],
    unique: [
        'Absorb',
        'Death',
        'Gears',
        'Infect',
        'Laser',
        'Mighty Wind',
        'Mimic',
        'Modified Electric',
        'Switch',
        'Teleport',
        'Wave',
    ],
    legendary: [
        'Assassin',
        'Blizzard',
        'Combo',
        'Element',
        'Growth',
        'Gun',
        'Hell',
        'Holy Sword',
        'Joker',
        'Landmine',
        'Metastasis',
        'Nuclear',
        'Sand Swamp',
        'Shield',
        'Solar',
        'Summoner',
        'Supplement',
        'Time',
        'Typhoon',
    ],
};
